package com.simplilearn.object;

import com.student.name.StudentName;

public class ObjectExample {

	
	public static void main(String[] args) {
		
		System.out.println("I am before Object");
		
		StudentName stu1= new StudentName(); 
		StudentName stu2= new StudentName(); 
		StudentName stu3= new StudentName(); 
		StudentName stu4= new StudentName(); 
		StudentName stu5= new StudentName(); 
		
		
		System.out.println(stu1.toString());
		System.out.println(stu2.toString());
		System.out.println(stu3.toString());
		System.out.println(stu4.toString());
		System.out.println(stu5.toString());
		
		// Is Object creation is Caustly operation ?// YES/ NO
		
		
		// 1. StudentName - class is getting loaded 
		// 2. Default constructor generated by compiler is getting called 
		// 3. All the variable is getting initialized 
		
		//what is initialisation? 

		
		
		
		
		
		System.out.println("I am after Object");
	}
}


